fix:新增项目负责人离职提示相关人员处理issue,配置项目报警时间
layotto/github-growth-hack pull request #22
Opened 2023-05-31 02:14 UTC by zhaoxuanqing

1.报警通知中若有离职同学更新对应文案
2.配置文件中新增可配置 time,projectName,owner
ps:configs文件并不在本次提交中.

2023-05-31 03:13 UTC, seeflood commented on src/notify.js
> +    "https://oapi.dingtalk.com/robot/send?access_token=0bf65479caed4a82735752ce39c8a9fa89e4fced2204f2e413faad81738e1d00",
别放明文token，不安全~

2023-05-31 04:35 UTC, seeflood commented on src/dao/dangerous_issue.js
> +        }
这块的判断有点绕，要不这样呢:
```js
	let content="";
	if (uid == null || uid.length == 0) {
	        content=`请${project}项目的相关`
     	}else{
	      uid.forEach((id) => {
	        content += `@${id} `;
	      });		
	}
```

2023-05-31 04:46 UTC, seeflood requested changes

2023-05-31 04:46 UTC, seeflood commented on src/dao/dangerous_issue.js
> +      let filteredIssues = k.filter((issue) => Number(issue.duration) <= 30);
过滤逻辑适合在上层改，不太适合在这个dao层改，会有问题（比如上层已经计算了这个issue的分数，但是调 insert 时却被过滤掉了）
这里说的“上层”指使用 dangerous_issue.js 的文件:
<img width="322" alt="image" src="https://github.com/layotto/github-growth-hack/assets/26001097/9c4a0aa5-6492-4193-b474-9c5a66df46b6">

2023-06-09 01:48 UTC, zhaoxuanqing commented on src/dao/dangerous_issue.js
> +        }
我来试着优化下.

2023-07-03 07:46 UTC, zhaoxuanqing commented on src/dao/dangerous_issue.js
> +        }
@seeflood 优化了一下.

2023-07-03 07:46 UTC, zhaoxuanqing commented on src/dao/dangerous_issue.js
> +      let filteredIssues = k.filter((issue) => Number(issue.duration) <= 30);
@seeflood 这里不加过滤了.

2023-07-03 07:51 UTC, zhaoxuanqing commented
@seeflood  优化了一下看下哈～

2023-07-03 08:46 UTC, seeflood commented on node_modules/node-fetch/package.json
> +      "/Users/zhaoxuanqing/Desktop/Project Documents/github-growth-hack"
为啥 node_modules 里会有你的文件路径呀？我不太懂nodejs，不清楚这样对不对

2023-07-03 09:03 UTC, zhaoxuanqing commented on node_modules/node-fetch/package.json
> +      "/Users/zhaoxuanqing/Desktop/Project Documents/github-growth-hack"
奇怪 我没有动过node_modules里的东西啊- - ..有一些变更可能是因为我的vscode的自动保存导致的

2023-07-03 09:17 UTC, seeflood requested changes

2023-07-03 09:17 UTC, seeflood commented on src/service/issue_scanner.js
> -              // console.log(data.rows[i]);
这个日志没必要删除?

2023-07-03 09:17 UTC, seeflood commented on src/dao/dangerous_issue.js
> +        let content = uid.map(id => id === project ? `请${project}项目的相关` : `@${id}`).join('');
![image](https://github.com/layotto/github-growth-hack/assets/26001097/df1df293-b4f0-4b3c-b2b4-9ed7b5395df2) 是不是得在 {id}后面加个空格?

2023-07-03 09:17 UTC, seeflood commented on node_modules/node-fetch/package.json
> +      "/Users/zhaoxuanqing/Desktop/Project Documents/github-growth-hack"
重新 npm install 能解决么?看下好弄么，不好弄就不管了

2023-07-03 09:17 UTC, seeflood commented on src/dao/dangerous_issue.js
> +      let filteredIssues = k.filter((issue) => Number(issue.duration) <= 30);
目前“判断30天内的issue"的过滤逻辑还是在dangerous_issue.js里，那还会有上述问题
![image](https://github.com/layotto/github-growth-hack/assets/26001097/1b165672-36cb-4545-b42f-ac68bdf83c81)

是不是可以把这个判断挪到调用 dangerous_issue.js 的文件里?
![image](https://github.com/layotto/github-growth-hack/assets/26001097/5bed6596-7cbd-451e-a169-8f5e52b03fb6)

2023-07-03 09:20 UTC, zhaoxuanqing commented on node_modules/node-fetch/package.json
> +      "/Users/zhaoxuanqing/Desktop/Project Documents/github-growth-hack"
估计是我在configs文件夹中使用了https请求更新githup仓库的JSON文件

2023-07-03 09:43 UTC, zhaoxuanqing commented on src/dao/dangerous_issue.js
> +        let content = uid.map(id => id === project ? `请${project}项目的相关` : `@${id}`).join('');
我没太明白为什么需要加空格.

2023-07-03 10:05 UTC, zhaoxuanqing commented on node_modules/node-fetch/package.json
> +      "/Users/zhaoxuanqing/Desktop/Project Documents/github-growth-hack"
重新install也不行  这个路径会造成影响吗.

2023-07-04 01:53 UTC, zhaoxuanqing commented on src/dao/dangerous_issue.js
> +      let filteredIssues = k.filter((issue) => Number(issue.duration) <= 30);
![image](https://github.com/layotto/github-growth-hack/assets/82356877/9503f427-2b5a-4dcd-bca4-ca2c70bc0fcd) 这样吗?

2023-07-04 02:12 UTC, closed without merging