fix: 新增项目负责人离职提示相关人员处理issue,配置项目报警时间
layotto/github-growth-hack pull request #23
Opened 2023-07-04 02:20 UTC by zhaoxuanqing

根据rw 优化代码.

2023-07-04 02:26 UTC, zhaoxuanqing commented
@seeflood  我重新 npm install 了下 node_modules 导致很多包的pgckage.json更新了 后面我想着能不能忽略掉node_modules。我根据您的建议把过滤放到了上层 看下是否合理.

2023-07-10 14:24 UTC, seeflood requested changes

2023-07-10 14:24 UTC, seeflood commented on src/service/weekly.js
> +    }
1. 你现在想实现啥效果，是想实现“大于30天的issue不算分、不报警”是么?
2. 感觉在这过滤没解决问题? 如果issue 大于30天，不会写库、但是会扣分，不一致
3. 你看下filterOutDangerousIssues 的实现，应该已经有30天相关的逻辑了

2023-07-10 14:27 UTC, seeflood commented on src/service/issue_scanner.js
> +              console.log(data.rows[i]);
哦我之前看错了，我以为你删掉了一行日志，但其实原先被注释了啊……那你随意，删掉也行

2023-07-10 14:28 UTC, seeflood requested changes

2023-07-10 14:28 UTC, seeflood commented on src/service/issue_scanner.js
> +            }
这里过滤也是一样的问题。
你看下listDangerousOpenIssues的代码，这个listDangerousOpenIssues也会调 filterOutDangerousIssues， 过滤逻辑可以写在 filterOutDangerousIssues 里

2023-07-10 14:29 UTC, seeflood commented on node_modules/@octokit/auth-token/package.json
要不就简单一点，把 node_modules加进 .gitignore 算了……

2023-07-10 14:39 UTC, seeflood commented on src/service/weekly.js
> +    }
之前filterOutDangerousIssues 里面已经有按baseline过滤的逻辑了，只不过baseline写死的是 2022-01-01
<img width="887" alt="image" src="https://github.com/layotto/github-growth-hack/assets/26001097/524bfc4e-9bd5-4d3a-82b1-8655074bd9a8">
你这个需求把baseline改成 “当前日期-k天" 就行了

2023-07-11 02:48 UTC, zhaoxuanqing commented on src/service/weekly.js
> +    }
是的 我刚开始没有想到分的问题.我根据您的建议修改了一下 您在看下

2023-07-12 07:52 UTC, seeflood approved these changes
LGTM

2023-07-12 07:52 UTC, merged