Laymaster
layotto/github-growth-hack pull request #27
Opened 2023-08-08 01:39 UTC by zhaoxuanqing

fix owners

2023-08-08 01:59 UTC, seeflood requested changes

2023-08-08 01:59 UTC, seeflood commented on src/dao/dangerous_issue.js
> +  insert: function (duration, owners,project, title, url) {
为啥owners是个数组……

2023-08-08 01:59 UTC, seeflood commented on src/metrics/issues.js
> +function filterOutDangerousIssues(issues, to,owner) {
为啥要改这个函数

2023-08-08 01:59 UTC, seeflood commented on src/service/weekly.js
> +        issue.owners,
上面把filterOutDangerousIssues改了，这为啥又没动filterOutDangerousIssues……
用不着改filterOutDangerousIssues吧，insert时候加个字段就行了

2023-08-08 02:18 UTC, zhaoxuanqing commented on src/metrics/issues.js
> +function filterOutDangerousIssues(issues, to,owner) {
insert加字段这值commit的时候拿不到 所以在这加的

2023-08-08 02:45 UTC, zhaoxuanqing commented on src/dao/dangerous_issue.js
> +  insert: function (duration, owners,project, title, url) {
是的啊. 但是每一个issue里都要有一个owner字段我才能做拼接啊

2023-08-09 01:39 UTC, zhaoxuanqing commented on src/metrics/issues.js
> +function filterOutDangerousIssues(issues, to,owner) {
> 为啥要修改这个函数

insert加字段这个值commit的时候拿不到所以在这个加的

2023-08-09 01:39 UTC, zhaoxuanqing commented on src/dao/dangerous_issue.js
> +  insert: function (duration, owners,project, title, url) {
> 对于项目啥所有者是一个数据库…… 一个只能属于一个所有者，不可能有多个所有者

是的啊。但是每个问题都会有一个所有者字段我可以做拼接啊

2023-08-09 01:40 UTC, zhaoxuanqing commented on src/dao/dangerous_issue.js
> +  insert: function (duration, owners,project, title, url) {
> 对于项目啥所有者是一个数据库…… 一个只能属于一个所有者，不可能有多个所有者

是的啊. 但是每一个issue里都要有一个owner字段我才能做拼接啊

2023-11-21 06:46 UTC, closed without merging